"""init

Revision ID: cf5a60e9bdd8
Revises: 
Create Date: 2025-10-28 19:56:35.305055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cf5a60e9bdd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVE', 'INACTIVE', name='estadoenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'USER', 'GUEST', name='rolenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.Column('cedula', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cedula'), 'user', ['cedula'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('operadora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id_usuario_created', sa.Uuid(), nullable=True),
    sa.Column('id_usuario_updated', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_created'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_updated'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('guia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=True),
    sa.Column('id_operadora', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('idiomas', sa.JSON(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id_usuario_created', sa.Uuid(), nullable=True),
    sa.Column('id_usuario_updated', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['id_operadora'], ['operadora.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_created'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_updated'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guia')
    op.drop_table('operadora')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_cedula'), table_name='user')
    op.drop_table('user')
    op.drop_table('rol')
    op.drop_table('estado')
    # ### end Alembic commands ###
